List<String> getLyrics() {
  return [
    '[Verse 1]',
    'You gave it all up, you had nothing left',
    'You should have kept some for yourself',
    'It´s easier to see in retrospect',
    'What I could have done to help',
    'We only get one life to get it right',
    'We only get one life to lead',
    'Now you cant keep this up night after night',
    'You need to find someone to be',
    '[Chorus]',
    'I want to shine a light',
    'On the things you do',
    'I want to shine a light',
    'On the things you do',
    '[Verse 2]',
    'I never wanted anything from you',
    'I never wanted much at all',
    'But you were always up to something new',
    'You never had that far to fall',
    '[Chorus]',
    'I want to shine a light',
    'On the things you do',
    'I want to shine a light',
    'On the things you do'
  ];

  /* ['Hope stopped the heart',
  'Lost beaten lie',
  'Cold walk the earth',
  'Love faded white',
  'Gave up the war',
  'I\'ve realized',
  'All will become',
  'All will arise',
  'Stay with me',
  'I hear them call the tide',
  'Take me in',
  'I see the last divide',
  'Hopelessy',
  'I leave this all behind',
  'And I am paralyzed',
  'When the broken fall alive',
  'Let the light take me too',
  'When the waters turn to fire',
  'Heaven, please let me through',
  'Far away, far away',
  'Sorrow has left me here',
  'Far away, far away',
  'Let the light take me in',
  'Fight back the flood',
  'One breath of life',
  'God, take the earth',
  'Forever blind',
  'And now the sun will fade',
  'And all we are is all we made',
  'Stay with me',
  'I hear them call the tide',
  'Take me in',
  'I see the last divide',
  'Hopelessy',
  'I leave this all behind',
  'And I am paralyzed',
  'When the broken fall alive',
  'Let the light take me too',
  'When the waters…'];
 */
}
